---
# origin: https://github.com/salecharohit/vagrant-ansible-alpine-docker/tree/master/docker
# NOTE: will fail with
# Error pulling image registry:2 - 500 Server Error: Internal Server Error (\"Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
- name: Install Docker for Alpine
  hosts: all
  become: yes

# https://github.com/freedomofpress/ansible-role-docker-registry
  vars:
    docker_registry_data_directory: /var/www/docker-registry
    docker_registry_expose_port: 5000
    
  tasks:
    - name: Create Docker registry docroot.
      file:
        state: directory
        path: "{{ docker_registry_data_directory }}"
        recurse: yes
        owner: vagrant
        group: vagrant        
        mode: "0755"
   # Failed to import the required Python library (Docker SDK for Python: docker
    - name: Run docker registry container
      docker_container:
        exposed_ports: "{{ docker_registry_expose_port }}"
        image: "registry:2"
        name: "registry"
        ports: "{{ docker_registry_expose_port }}:{{ docker_registry_expose_port }}"
        volumes:
          - "{{ docker_registry_data_directory }}:{{ docker_registry_data_directory }}"
        pull: "no"
        restart_policy: "always"
        state: "started"
        env:
          REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "{{ docker_registry_data_directory }}"

