---
- name: Install Docker for Alpine
  hosts: all
#  hosts: alpine
# NOTE: does not work:
# [WARNING]: Could not match supplied host pattern, ignoring: alpine
# BOX_HOSTNAME
  become: yes

# https://github.com/freedomofpress/ansible-role-docker-registry
  vars:
    docker_registry_data_directory: /var/www/docker-registry
    docker_registry_expose_port: 5000
    
  tasks:
    - name: Install wheel module
      pip:
        name: "{{item}}"
        state: present
      with_items:
       - wheel  
    - name: Start service docker, if not started
      service:
        name: docker
        state: started

