---
- name: Playbook for Alpine
  hosts:
    - all
    - localhost
# NOTE: add 'localhost' implicitly to prevent the command ansible-playbook playbook.yml
# from failing to apply with the warning
# [WARNING]: No inventory was parsed, only implicit localhost is available
# [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
#  hosts: alpine
# NOTE: remove to prevent failures running as vagrant user against localhost
# NOTE: does not work:
# [WARNING]: Could not match supplied host pattern, ignoring: alpine
# BOX_HOSTNAME
  become: yes

  vars:
    service_name: 'virtualbox-guest-additions'
  tasks:
    - name: Install wheel module
      pip:
        name: "{{item}}"
        state: present
      with_items:
       - wheel
    # https://pkgs.alpinelinux.org/contents?branch=edge&name=libxml2-utils&arch=x86_64&repo=main
    - name: Install xmllint tool
      apk:
        name: "{{item}}"
        state: present
      with_items:
       - libxml2-utils
    # ansible localhost -m command -a 'xmllint --version'
    # https://docs.ansible.com/ansible/latest/modules/command_module.html
    - name: Run xmllint command (try 1)
      command:
        # non-zero exit code
        cmd: xmllint --version 2>&1 || echo Done | tee /tmp/xmllint_version.log
        creates: /tmp/xmllint_version.log
        _uses_shell: yes
        # ignore_errors: yes
        # Unsupported parameters for (command) module: ignore_error
    # https://www.cyberciti.biz/faq/how-to-enable-and-start-services-on-alpine-linux/
    - name: Run xmllint command (try 2)
      command:
        # non-zero exit code
        cmd: sh -c "xmllint --version 2>&1 | tee /tmp/xmllint_version.log; echo 'Done'"
        creates: /tmp/xmllint_version.log
        _uses_shell: yes
    - name: "Start service {{service_name}}, if not started"
      # NOTE: this is still a valid YAML
      service: name="{{service_name}}" state=started enabled=yes

    - name: examine xml file
      command: xmllint --xpath '//*[local-name()=="Server"][@port == "-1"]' '/vagrant/test.xml'
      register: result
      ignore_errors: True

    - name: 'configure shutdown port'
      shell: 'echo "ABC"'
      when: result|failed

