# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'pp'

debug = ENV.fetch('DEBUG', false)
debug =  true if debug =~ /^(?:true|yes|1)$/i
# with pre-2.2.6 Vagrant (e.g. with Vagrant 2.0.2) this requires vagrant-alpine plugin to be present
box_hostname = ENV.fetch('BOX_HOSTNAME', 'alpine')

basedir = ENV.fetch('USERPROFILE', '')
basedir = ENV.fetch('HOME', '') if basedir == ''
basedir = basedir.gsub('\\', '/')

dir = File.expand_path(File.dirname(__FILE__))

# overrides the setting in Vagrantfile.yaml
box_name = 'alpine39'
vagrantfile_yaml = "#{dir}/Vagrantfile.yaml"
if File.exists?(vagrantfile_yaml)
  if debug
    puts "Loading '#{vagrantfile_yaml}'"
  end
  config_yaml = YAML::load_file( vagrantfile_yaml )
  if box_name !~ /\S/
    box_config = config_yaml[config_yaml[:boot]]
    box_name = box_config[:box_name]
  else
    box_config = config_yaml[box_name]
  end
  box_cpus = box_config[:box_cpus].to_i
  box_memory = box_config[:box_memory].to_i
  if debug
    pp box_config
  end
end

VAGRANTFILE_API_VERSION = '2'

# BOX_URL = 'https://app.vagrantup.com/alpine/boxes/alpine64/versions/3.7.0/providers/virtualbox.box'
BOX_URL = 'https://app.vagrantup.com/generic/boxes/alpine39/versions/3.0.10/providers/virtualbox.box'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = box_hostname
#  config.vm.hostname = box_hostname
# Vagrant attempted to execute the capability 'change_host_name' on the detect guest OS 'linux', but the guest doesn't support that capability.
  config_vm_default = box_config[:config_vm_default]
  config_vm_box_name = box_config[:config_vm_box_name]
  config.vm.box_url = "file://#{basedir}/Downloads/#{config_vm_box_name}"
  if debug
    puts "Configuring '#{config.vm.box}'"
  end

  config.vm.network :forwarded_port, host: 3000, guest: 3000
  config.ssh.forward_agent = true
  config.vm.boot_timeout = 600
  config.vm.synced_folder './', '/vagrant'
  config.vm.synced_folder './data', '/var/www/html', owner: 'vagrant', group: 'vagrant'
  config.vm.network :private_network, ip: '192.168.33.40'
  # if the shared folder do not work use scp 
  config.vm.provider 'virtualbox' do |vb|
    vb.customize ['modifyvm', :id, '--cpus', box_cpus ]
    vb.customize ['modifyvm', :id, '--memory', box_memory ]
    vb.customize ['modifyvm', :id, '--hwvirtex', 'on']
    vb.customize ['modifyvm', :id, '--pae', 'on']
    vb.customize ['modifyvm', :id, '--ioapic', 'on']
    vb.customize ['modifyvm', :id, '--accelerate3d', 'off']
    vb.customize ['modifyvm', :id, '--audio', 'none']
    vb.customize ['modifyvm', :id, '--usb', 'off']
  end

  config.vm.provision 'shell', inline: <<-SHELL

    # NOTE: avoid specifying release too strict
    PACKAGES='python3~=3.6 rsync jq xmlstarlet~=1.6.1 bash curl ansible~=2.7.17'
    sudo apk update
    sudo apk del python3
    apk add --update --no-cache $PACKAGES virtualbox-guest-additions
    sudo rm -rf /var/cache/apk/*
    sudo apk add
    sudo sh -c "echo vboxguest >> /etc/modules"
    sudo sed -i '/ipv6/d' /etc/modules
  SHELL
  if ! Vagrant.has_plugin?('vagrant-alpine')
    raise 'Need Vagrant plugin "vagrant-alpine"'   
  end

  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html
  # https://github.com/ansible/ansible-examples
  # https://github.com/salecharohit/vagrant-ansible-alpine-docker
  # see also: https://github.com/fulgorek/vagrant-ansible-docker-alpine
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'playbook.yml'
    ansible.verbose = true
  end
  # NOTE: try
  # https://github.com/jaimegildesagredo/server-expects
end


