# -*- mode: ruby -*-
# vi: set ft=ruby :

$rpmbuild_script = <<EOF

echo "Provisioning started, installing packages..."
sudo yum -y install rpmdevtools mock

echo "Setting up rpm dev tree..."
rpmdev-setuptree

echo "Linking files..."
ln -s /vagrant/SPECS/consul.spec $HOME/rpmbuild/SPECS/
find /vagrant/SOURCES -type f -exec ln -s {} $HOME/rpmbuild/SOURCES/ \\;

echo "Downloading dependencies..."
spectool -g -R rpmbuild/SPECS/consul.spec

echo "Building rpm..."
rpmbuild -ba rpmbuild/SPECS/consul.spec

echo "Copying rpms back to shared folder..."
mkdir /vagrant/RPMS
find $HOME/rpmbuild -type d -name "RPMS" -exec cp -r {} /vagrant/ \\;
find $HOME/rpmbuild -type d -name "SRPMS" -exec cp -r {} /vagrant/ \\;

EOF

tag = ENV.fetch('TAG', '')
basedir = ENV.fetch('USERPROFILE', '')
basedir = ENV.fetch('HOME', '') if basedir == ''
box_name = ENV.fetch('BOX_NAME', 'centos7-generic-x86_64.box')
master_box_memory = ENV.fetch('MASTER_BOX_MEMORY', '2048').to_i
agent_box_memory = ENV.fetch('AGENT_BOX_MEMORY', '512').to_i

Vagrant.configure(2) do |config|

  config.vm.box = 'boxcutter/centos72'
  box_name = 'centos7-generic-x86_64.box'
  config.vm.box_url = "file://#{basedir}/Downloads/#{box_name}"
  config.vm.hostname = 'config.example.com'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = master_box_memory
    vb.customize ['modifyvm', :id, '--cpus', '2']
  end
  config.vm.synced_folder '.', '/vagrant'
  config.vm.provision "shell", inline: $rpmbuild_script, privileged: false

end
