HOSTS:
  ubuntu-1604:
    roles:
      - agent
      - default
    platform: ubuntu-16.04-amd64
    image:  ubuntu:16.04 
    hypervisor: docker
    docker_cmd: ["/bin/systemd"]
    docker_preserve_image: true
    docker_image_commands:
      - apt-get install -yq wget net-tools
      - rm /lib/systemd/system/getty.target
