# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'
basedir = ENV.fetch('USERPROFILE', '')
basedir = ENV.fetch('HOME', '') if basedir == ''

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # set to false, if you do NOT want to check the correct VirtualBox Guest Additions version when booting this box
  if defined?(VagrantVbguest::Middleware)
    config.vbguest.auto_update = true
  end
  config.vm.box = 'ubuntu/xenial64-puppet'
  # https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-16.04-64-puppet
  # config.vm.box = 'puppetlabs/ubuntu-16.04-64-puppet'
  config_vm_box_name = 'ubuntu-16.04-64-puppet.box'
  config.vm.box_url = "file://#{basedir}/Downloads/#{config_vm_box_name}"

  # version only relevant for cloud images
  # config.vm.box_version = '1.0.1'
  config.vm.network :forwarded_port, guest: 5601, host: 5601
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 9300, host: 9300

  config.vm.provider :virtualbox do |v|
    v.name = 'ELK GD Timings Vagrant Box'
    v.customize ['modifyvm', :id, '--cpus', '2', '--memory', '2048']
  end

  config.vm.provision 'shell', inline: <<-END_OF_SHELL_SCRIPT
#!/usr/bin/env bash

# Install wget
sudo apt-get install -qqy curl wget git;

sed -e '/templatedir/ s/^#*/#/' -i.back /etc/puppet/puppet.conf

## set local/fastest mirror
mv /etc/apt/sources.list /etc/apt/sources.list.orig

cat > /etc/apt/sources.list <<EOF
deb mirror://mirrors.ubuntu.com/mirrors.txt xenial main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-updates main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-backports main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-security main restricted universe multiverse
EOF
sudo apt-get -qqy update

## set local timezone
export tz=`wget -qO - http://geoip.ubuntu.com/lookup | sed -n -e 's/.*<TimeZone>\(.*\)<\/TimeZone>.*/\1/p'` &&  sudo timedatectl set-timezone $tz

MODULE_PATH='/etc/puppetlabs/code/environments/production/modules'

mkdir -p $MODULE_PATH
if [ ! -d ${MODULE_PATH}/file_concat ]; then
 # puppet module install ispavailability/file_concat
 puppet module install 'electrical-file_concat'
fi
if [ ! -d ${MODULE_PATH}/apt ]; then
 # need recent version
 puppet module install 'puppetlabs-apt' --version '2.4.0'
fi
if [ ! -d ${MODULE_PATH}/java ]; then
 puppet module install 'puppetlabs-java'
fi
if [ ! -d ${MODULE_PATH}/elasticsearch ]; then
 puppet module install 'elasticsearch-elasticsearch'
fi
if [ ! -d ${MODULE_PATH}/logstash ]; then
 puppet module install 'elasticsearch-logstash'
fi
if [ ! -d ${MODULE_PATH}/nodejs ]; then
 puppet module install 'puppetlabs-nodejs'
fi
if [ ! -f /etc/init.d/kibana ]; then
 sudo cp /vagrant/kibana4_init /etc/init.d/kibana
 sudo sed -i 's/\r//' /etc/init.d/kibana
 sudo chmod +x /etc/init.d/kibana
 sudo update-rc.d kibana defaults
 wget -q http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
fi

# http://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/#
# https://stackoverflow.com/questions/37815790/syntaxerror-unexpected-token-function-async-await-nodejs
sudo apt-get install python-software-properties
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -qqy nodejs

  END_OF_SHELL_SCRIPT
  config.vm.provision 'shell', inline: '/opt/puppetlabs/bin/puppet apply --modulepath=/etc/puppetlabs/code/environments/production/modules /vagrant/manifests/default.pp'
end
