# -*- mode: ruby -*-
# # vi: set ft=ruby :

# origins:

# http://blog.scottlowe.org/2014/10/22/multi-machine-vagrant-with-yaml/
require 'yaml'
require 'pp'

basedir = ENV.fetch('USERPROFILE', '')
basedir = ENV.fetch('HOME', '') if basedir == ''
basedir = basedir.gsub('\\', '/')
debug = ENV.fetch('DEBUG', '')
debug = ( debug =~ (/^(true|yes|1)$/i))

dir = File.expand_path(File.dirname(__FILE__))

# Read nodes details
nodes = {}
nodes = YAML.load(<<-NODES)
---
- name: 'urugeas'
  box: 'centos'
  ram: '512'
  ipaddress: '172.17.8.102'

NODES
if debug
  nodes.each do |box|
    pp box
  end
end

# Read box details
configs = YAML::load( <<-BOXES)
---
:boot: 'centos'
# centos 7.3 x64 with Puppet 4.10.x
# origin:
# https://app.vagrantup.com/mbrush/boxes/centos7-puppet/versions/1.1.1/providers/virtualbox.box
'centos':
  :image_name: 'centos'
  :box_memory: '512'
  :box_cpus: '1'
  :box_gui: false
  :config_vm_newbox: false
  :config_vm_default: 'linux'
  :config_vm_box: 'centos'
  :image_filename: 'centos7-puppet-x86_64.box'

BOXES
if debug
  pp configs
end
modulepath = '/opt/puppetlabs/puppet/modules'

# bind_ip=127.0.0.1

box_config = {}

Vagrant.configure('2') do |config|
  nodes.each do |box|
    box_name = box['name']
    box_config = configs[box['box']]
    box_gui = box_config[:box_gui] != nil && box_config[:box_gui].to_s.match(/(true|yes|1)$/i) != nil
    box_cpus = box_config[:box_cpus].to_i
    box_memory = box_config[:box_memory].to_i
    newbox = box_config[:config_vm_newbox]
    image_filename = box_config[:image_filename]
    box_url = "file://#{basedir}/Downloads/#{image_filename}"
    config.vm.define box_name do |guest|
      guest.vm.box = box_config[:image_name]
      guest.vm.box_url = box_url
      guest.vm.network 'private_network', ip: box['ipaddress']
      guest.vm.provider :virtualbox do |vb|
        vb.name = box_name
        vb.memory = box_memory
      end

      config.vm.provision "shell", inline: <<-SHELL
	UPGRADE_PUPPET=false
        # optionally upgrade puppet to the latest version
	if $UPGRADE_PUPPET ; then
        sudo rpm -Uvh https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
        sudo yum install -y puppet-agent
	fi
	# https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-7-on-centos-7-via-yum
	# change locale of the base image
cat<<EOF>/etc/environment
LANG=en_US.utf-8
LC_ALL=en_US.utf-8
EOF
MODULE_PATH='#{modulepath}'
DIRECT_INSTALL_PUPPET_MODULES=false

if $DIRECT_INSTALL_PUPPET_MODULES ; then
  if [ ! -d ${MODULE_PATH}/stdlib ]; then
    puppet module install 'puppetlabs-stdlib' --version '4.22.0'
  fi
  if [ ! -d ${MODULE_PATH}/java ]; then
    puppet module install 'puppetlabs-java' --version '1.3.0'
  fi

  # for encrypted yaml
  # gem install hiera-eyaml --no-rdoc --no-ri
fi
# for integration testing
# default install for tomcat7
sudo yum install -y tomcat
      SHELL

      config.vm.synced_folder './' , '/vagrant'

      manifest = 'default.pp'

      # workaround for older Vagrant / Puppet 4 compatibility issue
      # NOTE: hiera arguments not set
      # config.vm.provision 'shell', inline: "puppet apply --modulepath=#{modulepath}:/vagrant/modules /vagrant/manifests/#{manifest}"

      config.vm.provision :puppet do |puppet|
        puppet.hiera_config_path = 'hiera.yaml'
        puppet.module_path       = 'modules'
        puppet.manifests_path    = 'manifests'
        puppet.manifest_file     = manifest
        puppet.options           = "--verbose --modulepath #{modulepath}:/vagrant/modules "
        puppet.working_directory = '/tmp/vagrant-puppet'
        config.vm.synced_folder 'hieradata/', '/tmp/vagrant-puppet/hieradata'
      end
      # based on: https://github.com/andrewwardrobe/PuppetIntegration/blob/master/Vagrantfile
      # NOTE: may also will to install InSpec https://github.com/inspec/inspec
      config.vm.provision 'shell', inline: <<-EOF
        # https://www.softwarecollections.org/en/scls/rhscl/rh-ruby23/
        # https://access.redhat.com/solutions/527703
        yum install -q -y centos-release-scl yum-utils
        yum-config-manager --enable rhel-server-rhscl-7-rpms
        yum install -q -y rh-ruby23
        # usual culmination is with embarking in a new bash environment
        source scl enable rh-ruby23
        SCL_BASE_PATH='/opt/rh/rh-ruby23/root'
        # NOTE: To make visible to root user, install alternatives in /usr/bin
        # not in /usr/local/bin
        update-alternatives --install /usr/bin/ruby ruby ${SCL_BASE_PATH}/usr/bin/ruby 10
          update-alternatives --install /usr/bin/gem gem ${SCL_BASE_PATH}/usr/bin/gem 10
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${SCL_BASE_PATH}/usr/lib64
        RAKE_VERSION='12.3.1'
        gem install --no-ri --no-rdoc rake:${RAKE_VERSION} specinfra:2.76.1 net-ssh:5.0.2 rspec:3.8.0 rspec-core:3.8.0 rspec-support:3.8.0 rspec-its:1.2.0 rspec-expectations:3.8.1 serverspec:2.41.3
        update-alternatives --install /usr/bin/rake rake ${SCL_BASE_PATH}/usr/local/share/gems/gems/rake-${RAKE_VERSION}/exe/rake 10
        cd /vagrant/local_test
        rake spec
      EOF
      end
  end
end
